version: 2
updates:
  - package-ecosystem: "composer"
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'feat: '
      prefix-development: 'chore: '
    cooldown:
      default-days: 3
      semver-patch-days: 3
      semver-minor-days: 7
      semver-major-days: 14
    groups:
      composer-development:
        dependency-type: development
        update-types:
          - minor
          - patch
      composer-production:
        dependency-type: production
        update-types:
          - patch

  - package-ecosystem: "npm"
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'feat: '
      prefix-development: 'chore: '
    cooldown:
      default-days: 3
      semver-patch-days: 3
      semver-minor-days: 7
      semver-major-days: 14
    groups:
      npm-development:
        dependency-type: development
        update-types:
          - minor
          - patch
      npm-production:
        dependency-type: production
        update-types:
          - patch

  - package-ecosystem: "github-actions"
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'ci: '
    cooldown:
      default-days: 3
    groups:
      actions-minor:
        update-types:
          - minor
          - patch
