import { faker } from '@faker-js/faker';

export const contexts = [
  {
    text: faker.lorem.word(),
  },
  {
    element: 'input',
    html: `<span>${faker.lorem.word()}</span>`,
    text: faker.lorem.word(),
    name: faker.lorem.word(),
    value: faker.lorem.word(),
    disabled: true,
    href: faker.internet.url(),
    classes: `${faker.lorem.word()} ${faker.lorem.word()}`,
    attributes: {
      [faker.lorem.word()]: faker.lorem.word(),
      [faker.lorem.word()]: faker.lorem.word(),
    },
    preventDoubleClick: true,
    isStartButton: true,
  },
  {
    element: 'a',
    html: `<span>${faker.lorem.word()}</span>`,
    text: faker.lorem.word(),
    name: faker.lorem.word(),
    value: faker.lorem.word(),
    disabled: true,
    href: faker.internet.url(),
    classes: `${faker.lorem.word()} ${faker.lorem.word()}`,
    attributes: {
      [faker.lorem.word()]: faker.lorem.word(),
      [faker.lorem.word()]: faker.lorem.word(),
    },
    preventDoubleClick: true,
    isStartButton: true,
  },
  {
    element: 'button',
    html: `<span>${faker.lorem.word()}</span>`,
    text: faker.lorem.word(),
    name: faker.lorem.word(),
    value: faker.lorem.word(),
    disabled: true,
    href: faker.internet.url(),
    classes: `${faker.lorem.word()} ${faker.lorem.word()}`,
    attributes: {
      [faker.lorem.word()]: faker.lorem.word(),
      [faker.lorem.word()]: faker.lorem.word(),
    },
    preventDoubleClick: true,
    isStartButton: true,
  },
  {
    html: `<span>${faker.lorem.word()}</span>`,
    text: faker.lorem.word(),
    name: faker.lorem.word(),
    type: 'reset',
    value: faker.lorem.word(),
    disabled: true,
    href: faker.internet.url(),
    classes: `${faker.lorem.word()} ${faker.lorem.word()}`,
    attributes: {
      [faker.lorem.word()]: faker.lorem.word(),
      [faker.lorem.word()]: faker.lorem.word(),
    },
    preventDoubleClick: true,
    isStartButton: true,
  },
];
