name: Dependabot

on:
  pull_request:

permissions:
  contents: read

jobs:
  auto-merge:
    name: Auto Merge
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    outputs:
      dependency-type: ${{ steps.metadata.outputs.dependency-type }}
      update-type: ${{ steps.metadata.outputs.update-type }}
      package-ecosystem: ${{ steps.metadata.outputs.package-ecosystem }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Metadata
        id: metadata
        uses: dependabot/fetch-metadata@21025c705c08248db411dc16f3619e6b5f9ea21a # v2.5.0
      - name: Debug
        env:
          OUTPUT: ${{ toJson(steps.metadata.outputs) }}
        run: echo "$OUTPUT"
      - name: Merge
        if: ${{ steps.metadata.outputs.dependency-group != '' && steps.metadata.outputs.update-type != 'version-update:semver-major' }}
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Skip Merge
        if: ${{ steps.metadata.outputs.dependency-group == '' || steps.metadata.outputs.update-type == 'version-update:semver-major' }}
        run: echo "Not merging PR as it does not belong to a dependency group or is a major version update."
